version: '3.5'

services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'ativ7'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'soo123'
            MYSQL_ROOT_PASSWORD: '1@#!R00T0(*&'
        ports:
        - '3306:3306'
        expose:
        - '3306'

    mongodb:
        image: mongo:5.0
        ports:
        - 27017:27017
        volumes:
        - ./volumes/mongo:/data/ativ7
        restart: always
        environment:
        - MONGO_INITDB_ROOT_USERNAME=user
        - MONGO_INITDB_ROOT_PASSWORD=soo123
