version: '3.5'
name: fazenda-vertical

networks:
  api_network:
  db_network:
  rabbit_network:

services:
  simulador-dispositivos:
    build:
      context: ./dispositivos
      dockerfile: Dockerfile.manager
    networks:
      - rabbit_network
    environment:
      RABBITMQ_CONNECTION_STRING: amqp://fila-soo:Grupo05SOO@rabbit:5672
      SENSOR_QUEUE: estante-1
      INTERVAL_SECONDS: 3
  
  simulador-dispositivos-2:
    build:
      context: ./dispositivos
      dockerfile: Dockerfile.manager
    networks:
      - rabbit_network
    environment:
      SENSOR_QUEUE: estante-1
      INTERVAL_SECONDS: 4

  simulador-dispositivos-3:
    build:
      context: ./dispositivos
      dockerfile: Dockerfile.manager
    networks:
      - rabbit_network
    environment:
      SENSOR_QUEUE: estante-1
      INTERVAL_SECONDS: 5
    
  rabbit:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: fila-soo
      RABBITMQ_DEFAULT_PASS: Grupo05SOO
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit_network
    restart: on-failure
    volumes:
      - ./volumes/rabbit:/var/lib/rabbitmq/mnesia

  api:
    build:
      context: ./api
    networks:
      - api_network
      - db_network
      - rabbit_network
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://database:3306/fazenda-vertical'
      RABBITMQ_HOST: rabbit
      RABBITMQ_QUEUE: estante-1

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'fazenda-vertical'
      MYSQL_USER: 'mysql-soo'
      MYSQL_PASSWORD: 'Grupo05@SOO'
      MYSQL_ROOT_PASSWORD: '1@#!R00T0(*&'
    ports:
      - '3306:3306'
    networks:
      - db_network
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  frontend:
    build:
      context: front-end
    networks:
      - api_network
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: 'http://api:8080/agrotech'

  socket-client:
    build:
      context: socket-client
    networks:
      - api_network
    environment:
      REACT_APP_HOST_SOCKET_URL: 'http://localhost:8080/agrotech/ws'
      PORT: 3001
    ports:
      - '3001:3001'
