version: '3.5'

networks:
  rabbit_network:
  db_network:

services:
  ## sensor:
  ##   build: './dispositivos/Dockerfile.sensor'
  ##   env_file: ./dispositivos/.env
  

  rabbit: 
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: fila-soo
      RABBITMQ_DEFAULT_PASS: Grupo05-SOO
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit_network
    restart: on-failure
    volumes:
      - ./volumes/rabbit:/var/lib/rabbitmq/mnesia

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'fazenda-vertical'
      MYSQL_USER: 'mysql-soo'
      MYSQL_PASSWORD: 'Grupo05@SOO'
      MYSQL_ROOT_PASSWORD: '1@#!R00T0(*&'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - db_network
    volumes:
      - ./volumes/mysql:/var/lib/mysql
