version: '3.5'

networks:
  rabbit_network:
  db_network:

services:
  dispositivo_1:
    build:
      context: ./dispositivos
      dockerfile: Dockerfile.sensor
    env_file: ./dispositivos/sensor.env
    restart: on-failure
    environment:
      SENSOR_QUEUE: 'dispositivo-1'
      CATEGORIA_ID: 1
      CATEGORIA_NOME: 'Temperatura'
      CATEGORIA_MEDIDA: 'ºC'
      DISPOSITIVO_ID: 1
      POSICAO_VERTICAL: 1
      POSICAO_HORIZONTAL: 1
    networks:
      - rabbit_network
#  
#  dispositivo_2:
#    build:
#      context: ./dispositivos
#      dockerfile: Dockerfile.sensor
#    env_file: ./dispositivos/sensor.env
#    restart: on-failure
#    environment:
#      DISPOSITIVO_ID: 2
#      SENSOR_QUEUE: 'dispositivo-2'
#      CATEGORIA_ID: 2
#      CATEGORIA_NOME: 'Humidade do Ar'
#      CATEGORIA_MEDIDA: '%'
#      POSICAO_VERTICAL: 1
#      POSICAO_HORIZONTAL: 1
#    networks:
#      - rabbit_network
#
#  dispositivo_3:
#    build:
#      context: ./dispositivos
#      dockerfile: Dockerfile.sensor
#    env_file: ./dispositivos/sensor.env
#    restart: on-failure
#    environment:
#      DISPOSITIVO_ID: 3
#      SENSOR_QUEUE: 'dispositivo-3'
#      CATEGORIA_ID: 3
#      CATEGORIA_NOME: 'Humidade do Solo'
#      CATEGORIA_MEDIDA: '%'
#      POSICAO_VERTICAL: 1
#      POSICAO_HORIZONTAL: 1
#    networks:
#      - rabbit_network
#  
#  dispositivo_4:
#    build:
#      context: ./dispositivos
#      dockerfile: Dockerfile.sensor
#    env_file: ./dispositivos/sensor.env
#    restart: on-failure
#    environment:
#      DISPOSITIVO_ID: 4
#      SENSOR_QUEUE: 'dispositivo-4'
#      CATEGORIA_ID: 1
#      CATEGORIA_NOME: 'Temperatura'
#      CATEGORIA_MEDIDA: 'ºC'
#      POSICAO_VERTICAL: 2
#      POSICAO_HORIZONTAL: 1
#    networks:
#      - rabbit_network
#
  rabbit: 
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: fila-soo
      RABBITMQ_DEFAULT_PASS: Grupo05SOO
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit_network
    restart: on-failure
    volumes:
      - ./volumes/rabbit:/var/lib/rabbitmq/mnesia
  
  api:
    build:
      context: ./api
    networks:
      - db_network
    restart: on-failure
    ports:
      - '8080:8080'

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'fazenda-vertical'
      MYSQL_USER: 'mysql-soo'
      MYSQL_PASSWORD: 'Grupo05@SOO'
      MYSQL_ROOT_PASSWORD: '1@#!R00T0(*&'
    ports:
      - '3306:3306'
    networks:
      - db_network
    volumes:
      - ./volumes/mysql:/var/lib/mysql
